import productA from '../../assets/p2.png'
import productB from '../../assets/Jumper-PNG-Image.png'
import productC from '../../assets/Jumper-Sweater-PNG.png'
  export const popularProducts = [
    {
      id:1,
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    },
    {
      id:2,
      img:productA,
    },
    {
      id:3,
      img:"https://www.pngall.com/wp-content/uploads/6/Sweater-PNG-Image-File.png",
    },
    {
      id:4,
      img:productB,
    },
    {
      id:5,
      img:"https://www.pngall.com/wp-content/uploads/6/Sweater-PNG-High-Quality-Image.png",
    },
    {
      id:6,
      img:"https://d3o2e4jr3mxnm3.cloudfront.net/Rocket-Vintage-Chill-Cap_66374_1_lg.png",
    },
    {
      id:7,
      img:productC,
    },
    {
      id:8,
      img:"https://www.pngarts.com/files/3/Women-Jacket-PNG-High-Quality-Image.png",
    },
    {
      id:9,
      img:"https://www.pngall.com/wp-content/uploads/6/Sweater-Transparent.png",
    },
    {
      id:10,
      img:"https://www.pngall.com/wp-content/uploads/6/Sweater-PNG-Photo.png",
    },
    {
      id:11,
      img:"https://www.pngall.com/wp-content/uploads/6/Sweater-PNG-File.png",
    },
    {
      id:12,
      img:"https://www.pngall.com/wp-content/uploads/6/Sweater.png",
    },
    {
      id:13,
      img:"https://www.pngall.com/wp-content/uploads/6/Sweater-PNG-Pic.png",
    },
    {
      id:14,
      img:"https://www.pngall.com/wp-content/uploads/13/Snapback-PNG-Photo.png",
    },
    {
      id:15,
      img:"https://www.pngall.com/wp-content/uploads/13/Snapback-PNG-Photos.png",
    },
    {
      id:16,
      img:"https://www.pngall.com/wp-content/uploads/13/Snapback-Hat-PNG-Pic.png",
    },
    {
      id:17,
      img:"https://www.pngall.com/wp-content/uploads/5/Pant-PNG-Transparent-HD-Photo.png",
    },
    {
      id:18,
      img:"https://www.pngall.com/wp-content/uploads/5/Pant-PNG-Download-Image.png",
    },
    {
      id:19,
      img:"https://www.pngall.com/wp-content/uploads/5/Pant-PNG-Image-File.png",
    },
    {
      id:20,
      img:"https://www.pngall.com/wp-content/uploads/5/Pant-PNG-High-Quality-Image.png",
    },
    {
      id:21,
      img:"https://www.pngall.com/wp-content/uploads/5/Cotton-Pant-PNG-Image-HD.png",
    },
    {
      id:22,
      img:"https://www.pngall.com/wp-content/uploads/4/Short-Skirt-Transparent.png",
    },
    {
      id:23,
      img:"https://www.pngall.com/wp-content/uploads/4/Skirt-Transparent.png",
    },
    {
      id:24,
      img:"https://www.pngall.com/wp-content/uploads/4/Skirt-PNG-Download-Image.png",
    },
    {
      id:25,
      img:"https://www.pngall.com/wp-content/uploads/2016/07/Dress-PNG-File.png",
    },
    {
      id:26,
      img:"https://www.pngall.com/wp-content/uploads/2016/07/Dress.png",
    },
    {
      id:27,
      img:"https://www.pngall.com/wp-content/uploads/2016/07/Dress-PNG-Image.png",
    },
    {
      id:28,
      img:"https://www.pngall.com/wp-content/uploads/2016/07/Dress-PNG-HD.png",
    },
    {
      id:29,
      img:"https://www.pngall.com/wp-content/uploads/2016/04/Jeans-PNG-Images.png",
    },
    {
      id:30,
      img:"https://www.pngall.com/wp-content/uploads/2016/04/Jeans-Download-PNG.png",
    },
    {
      id:31,
      img:"https://www.pngall.com/wp-content/uploads/2016/04/Jeans-PNG-Image.png",
    },
    {
      id:32,
      img:"https://www.pngall.com/wp-content/uploads/2016/04/Jeans-Transparent.png",
    },
    
  ]